### ISSUE TITLE
The nav bar and the "intro" section coincides

### ISSUE THREAD

**Issue by DEBSUBHRO** [LBRYFoundation/lbry.fund#29]
The nav bar elements and the "intro" section coincides (as provided in the picture)
![0](https://user-images.githubusercontent.com/42496309/66192422-0d19bf80-e6ae-11e9-808d-a3c6f4179ce4.PNG)

**Comment by tzarebczan** [comment]
Nice catch - seems to happen on small screens.  Thanks for filing @DEBSUBHRO !

**Comment by wale-bant** [comment]
Hi there, can i work on this?
